name: CD To Lightsail

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

jobs:
  create_ssh_key:
    runs-on: ubuntu-latest
    steps:
      - name: Create known hosts
        run: |
          mkdir ~/.ssh
          touch ~/.ssh/known_hosts
          
        
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with: 
          key: ${{ secrets.ACTION_LIGHTSAIL_SECRET }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
     
        
      - name: install rsync
        run: sudo apt-get install rsync
      
      - name: rsync deployments
        run: sudo rsync -avz ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.FOLDER_OF_APP }}

