name: CD To Lightsail

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

jobs:
  create_ssh_key:
    runs-on: ubuntu-latest
    steps:
      - name: install rsync
        run: sudo apt-get install rsync
        
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: |
          npm ci
          npm run build
          ls -la
          pwd

      - name: build & ssh-deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACTION_LIGHTSAIL_SECRET }}
          ARGS: "-rltgoDzvO"
          SOURCE: "docs"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: ${{ secrets.FOLDER_OF_APP }}
